version: '3.8'

services:
  mysql:
    image: mysql:latest
    ports:
      - '${DB_PORT:-3306}:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: '${DB_DATABASE}'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
            retries: 3
            timeout: 5s

  redis:
    image: redis:latest
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - '8080:80'
    environment:
        MYSQL_USERNAME: '${DB_USERNAME}'
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        PMA_HOST: mysql
        UPLOAD_LIMIT: 100M
    depends_on:
      - mysql

volumes:
  mysql_data:
  redis_data: